version: '3.8'
services:
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - backend
  backend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/dalta
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: sleep infinity
volumes:
  postgres-data:
